### ISSUE TITLE
EIO error on running on pico

### ISSUE THREAD

**Issue by wx4cb** [jposada202020/MicroPython_ICM20948#1]
currently trying to run the "simple test" program on a rapi pico with the [waveshare 10dof board](https://www.waveshare.com/wiki/Pico-10DOF-IMU). their documentation sucks and their class only works by itself in the example program cus of the way they have used globals.

whenever i try and run just a simple test i get the following error. As you can see i have the libraries uploaded to the pico. anythoughts appreciated.

![image](https://github.com/jposada202020/MicroPython_ICM20948/assets/1495297/4c16eb8c-ddff-45de-a681-0a0bcf46f807)

**Comment by jposada202020** [comment]
Hello, not sure, they have different versions, as I can see, they new version no longer use the ICM20948.
I will verify the pins used, in the example pins used are different from where I see in the figure (GP6, GP7).
Also, sensor I2C address used is different.

Hope that helps, sadly do not have that hardware to verify these assumptions.
This is an exercise for the reader :). Good Luck!

**Comment by jposada202020** [comment]
@wx4cb hello, any luck?
