### ISSUE TITLE
Compass and rotation

### ISSUE THREAD

**Issue by minhanh1234** [jposada202020/MicroPython_ICM20948#2]
Hi

Would you know if this chip can calculate compass angle like most magnetometer and would you have any example code to calculate rotation count? Example if i rotate the gyro on a table? (Example: 2 counter clockwise ration)

Thanks

**Comment by jposada202020** [comment]
Hello you can adapt the code found here https://github.com/jposada202020/MicroPython_QMC5883L/blob/4bbf82736983dea0722912a65c02f2f77c03b55e/examples/qmc5883l_magnetic_compass.py#L4 for what you are looking for. Cheers
